### ISSUE TITLE
Accept requests to create multiple resources

### ISSUE THREAD

**Issue by jfoy** [univedo/api2go#61]
JSON API specifies rules for requests to create multiple resources: http://jsonapi.org/format/#crud-creating-multiple-resources . Requests creating more than one item are explicitly disallowed in api.go; are there reasons to rule out POSTs describing multiple items, or is this just a feature we haven't gotten to write yet?

**Comment by wwwdata** [comment]
You are right this is still a missing feature if you are using the api resource to create a rest app. However if you in marshal a json with the api2go unmarshal method it should work. 

I guess we should change the signature of the create method of a resource to return multiple ids. You are welcome to submit a pull request if you like. Otherwise I think I can do it on the weekend or next week.

**Comment by wwwdata** [comment]
updating multiple resources is also in the specification and currenctly not supported: http://jsonapi.org/format/#crud-updating-multiple-resources

**Comment by sharpner** [comment]
Creating and Updating multiple resources is not in the RC3 spec anymore. So I'm closing this.
