### ISSUE TITLE
Documentation example and integration

### ISSUE THREAD

**Issue by alexjp** [univedo/api2go#69]
Hi,

I am a beginner in go, but would love to use something in golang for my ember projects.
But as i am a beginner in go, never managed to make this as a backend. Also trying some frameworks in go, seem very nice, but how would i integrate this in revel or beego or goji or gorilla ?

So, question : Is there an example for this with database ?
Also , is it possible to integrate this into revel or beego, etc perfectly ?

Thanks.

**Comment by wwwdata** [comment]
Hi,

we currently do not have a complete example.

Beego or Revel are complete frameworks for rendering a static website, as far as I know. If you want to use our API Methods to generate the routes for you automatically, you get an api2go.API Object. On that you can call the `Handler()` method, to retrieve a standard go `http.Handler` that can be used everywhere. You could for example do your own ServeMux and use our api2go API and one of your favored frameworks together, see: https://godoc.org/net/http#ServeMux

Another approach would be to completely configure the Routes in the other Framework and just use our Marshal/Unmarshal Methods. 

The Idea behind the API was to get a quick start into setting up a complete json only api, because we also use ember with ember-json-api in our frontend and need nothing else from the backend.

You should be able to use any database you like with our project, as long as you keep our convention for the related structs. So you always have Fields for the IDs and the related structs as mentioned in our Readme.

So: What are you planning to do? Which database and what else does your backend need apart from jsonapi compliant json generation?

**Comment by alexjp** [comment]
Hi, 
I managed to do the Marshal/Unmarshal in goji, but the routes would be great also.

What i would need for my backend would be : jsonapi json marshlling, routes, controllers ( done and done for this ), database ( maybe gorm is the best go orm right now, or beego orm ), some sort of authoring and business logic services support. 

I came from the rails world. Right now i am using sails.js for my backend. Do you plan to expand api2go? Or is it going to be a lightweight framework/library ?

I need to increase my golang skills before i can do beego integrations like you said. Sorry if what i ask is very easy to do, i am beginning at golang.

Thanks!

**Comment by wwwdata** [comment]
hi, yes for sql databases I can recommend gorm. I almost tried them all. In the go world everything is pretty new and you won't find a feature complete orm that can do everything at the moment and also not a large framework like rails afaik. It's more around small libraries that you can combine. 

At the moment we do not plan to make more out of api2go, but if you have some great ideas what we could do, share them with us :)

For the business logic and services stuff: I am facing that problem too where you have a lot of dependencies in your code and at the moment I am manually instantiating everything and doing DI by hand. This little library here looks pretty awesome to do it automatically because the manual stuff is always error prone: https://godoc.org/github.com/facebookgo/inject

**Comment by sharpner** [comment]
I will close this for now.
