### ISSUE TITLE
HTTP HEAD requests and/or Cacheing Functionality

### ISSUE THREAD

**Issue by ben-crowhurst** [univedo/api2go#70]
Is it true to state api2go fails to address cacheing in any form?  Even a HTTP HEAD request seems blocked (405 Method Not Allowed)

**Comment by sharpner** [comment]
I'll look into it

**Comment by wwwdata** [comment]
yes, currently the api does not support HEAD requests. But we could easily integrate that.

**Comment by sharpner** [comment]
the addition of HEAD requests is not the problem. 

The current architecture does not allow changing the Status Code within the DataSource or within a Controller. 

In order to let users implement Caching within a DataSource this function must be implemented.

But for the meantime, you could wrap the api.Handler() :

```go
func wrapAPIHandler() http.HandlerFunc {
  api := api2go.NewAPI("v1")
  handler := api.Handler()
  return func(w http.ResponseWriter, r *http.Request) {
    //TODO implement caching =)
    handler.ServeHTTP(w, r)
  }
}
```

**Comment by sharpner** [comment]
@ben-crowhurst did this help you out?

**Comment by ben-crowhurst** [comment]
Bit of a work around but it does the job

thank you.

**Comment by sharpner** [comment]
you're welcome.
