### ISSUE TITLE
Replace CamelCase with Dashes

### ISSUE THREAD

**Issue by wwwdata** [univedo/api2go#91]
jsonapi now recommends to use dashes for naming of fields

> It is recommended that resource types, attribute names, and association names be "dasherized"; i.e. consist of only lower case alphanumeric characters and dashes (U+002D HYPHEN-MINUS, "-").

> It is also recommended that resource types be pluralized. Dasherized and pluralized resource types can be used as URL segments without translation, as discussed below.

**Comment by sharpner** [comment]
Since it's only recommended by the spec and not a must, I would suggest implementing a reflect tag in order to let the user rename fields if wanted.

Something like: `jsonapi:name="hyphened-name"` on a struct field. 

The alternative would be to reintroduce conventions again like "every uppercase letter followed by a lowercase letter will be replaced with a lowercase hyphened version of it". But this would also have to be configurable and might introduce new "magic problems". 

What do you guys think?

**Comment by wwwdata** [comment]
hm, I think this is a very good idea. We should take a look how client side libraries do it. But we should look at some client side libraries and if they all expect the dash-naming we should make it the default.

But no matter what our "default" is, the custom-name idea is awesome!
