### ISSUE TITLE
Error when passing anonymous struct to MarshalToJSON

### ISSUE THREAD

**Issue by lukevers** [univedo/api2go#96]
From the README:

> If the struct already has a field named ID, or Id, it will be ignored automatically. If your ID field has a different name, please use the json ignore tag.

My code:

```go
j, err := jsonapi.MarshalToJSON(&struct{
	Status string
	ID string
}{
	Status: "success",
	ID: "test",
})
```
The error:

> interface conversion: *struct { Status string; ID string } is not jsonapi.MarshalIdentifier: missing method GetID

I also tried `Id` like the README also said, and both of them give me the same error.

**Comment by wwwdata** [comment]
you cannot Marshal an anonymous struct anymore. Every struct that needs to be marshalled must implement the `MarshalIdentifier` interface like mentioned in the error message that you got. 

I am sorry that the Readme confused you about this. This ignoring of fields with `ID` in their name is just an unnecessary bonus that api2go does for you. I would even suggest that we remove this completely so that the user is forced to use the json ignore tag. 

You can also look at our example in the example folder on how to implement the `GetID` method

**Comment by lukevers** [comment]
Thanks for responding quickly! I also noticed that `ID` error in a non-anonymous struct, and when I saw it happening here too I thought I'd let you guys know. I'll close this issue since it seems I just misunderstood what was going on.

**Comment by wwwdata** [comment]
ok :) just implement the `GetID` method like here in the example for the structs that you want to Marshal and it will work: https://github.com/univedo/api2go/blob/master/examples/crud_example.go#L47
